SUPABASE_URL = "https://jhoduzvsqrpwsujvnsvn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impob2R1enZzcXJwd3N1anZuc3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2MDgzMzAsImV4cCI6MjA5NTE4NDMzMH0.34THBSza4fOcG0kZM7qD9SknTA0EoxxQPiij10QI35g"
